name: Wheel jiter

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.13'
      android_api:
        description: 'Android API level'
        required: false
        default: '24'
      jiter_version:
        description: 'jiter version tag (optional, uses latest if not specified)'
        required: false
  push:
    paths:
      - '.github/workflows/wheel-jiter.yml'
      - '.github/workflows/build-android-wheel-dispatch.yml'
      - '.github/scripts/build/**'

jobs:
  build-jiter:
    uses: ./.github/workflows/build-android-wheel-dispatch.yml
    permissions:
      contents: write
      actions: write
    with:
      library-name: 'jiter'
      git-repository: 'pydantic/jiter'
      library-version: ${{ github.event.inputs.jiter_version }}
      python-version: ${{ github.event.inputs.python_version || '3.13' }}
      android-api: ${{ github.event.inputs.android_api || '24' }}
