name: Wheel zstandard

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.13'
      ndk_version:
        description: 'Android NDK version'
        required: false
        default: 'r26d'
      android_api:
        description: 'Android API level'
        required: false
        default: '24'
      zstd_version:
        description: 'zstandard version tag (optional, uses latest if not specified)'
        required: false
  push:
    paths:
      - '.github/workflows/wheel-zstandard.yml'
      - '.github/workflows/build-android-wheel-dispatch.yml'
      - '.github/scripts/build/**'

jobs:
  build-zstd:
    uses: ./.github/workflows/build-android-wheel-dispatch.yml
    permissions:
      contents: write
      actions: write
    with:
      library-name: 'zstandard'
      git-repository: 'indygreg/python-zstandard'
      library-version: ${{ github.event.inputs.zstd_version }}
      python-version: ${{ github.event.inputs.python_version || '3.13' }}
      android-api: ${{ github.event.inputs.android_api || '24' }}