name: Wheel pydantic-core

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.13'
      android_api:
        description: 'Android API level'
        required: false
        default: '24'
      version_tag:
        description: 'pydantic-core version tag (optional, uses latest if not specified)'
        required: false
  push:
    paths:
      - '.github/workflows/wheel-pydantic-core.yml'
      - '.github/workflows/build-android-wheel-dispatch.yml'
      - 'scripts/build/**'

jobs:
  build-pydantic-core:
    uses: ./.github/workflows/build-android-wheel-dispatch.yml
    permissions:
      contents: write
      actions: write
    with:
      library_name: 'pydantic-core'
      git_repository: 'pydantic/pydantic-core'
      version_tag: ${{ github.event.inputs.version_tag}}
      target_python_version: ${{ github.event.inputs.python_version || '3.13' }}
      android_api: ${{ github.event.inputs.android_api || '24' }}
